### ISSUE TITLE
Links for KnowIt-VQA are down

### ISSUE THREAD

**Issue by simon-ging** [noagarcia/ROLL-VideoQA#2]
Hey, 

I just dropped you a mail not realizing you are also the owner of the KnowIt-VQA dataset.

Could you please reupload the following links for KnowIt-VQA?

https://knowit-vqa.s3-ap-northeast-1.amazonaws.com/knowit-vrd.zip
https://knowit-vqa.s3-ap-northeast-1.amazonaws.com/knowit_data.zip

Currently it is not at all possible to reproduce your results for ROLL since the data for KnowIt-VQA is missing and for TVQA+ you don't provide anything.

Best,

S. Ging

**Comment by estelleafl** [comment]
Hi!
Any update on this?
Thank you
Best

**Comment by Pwoer-zy** [comment]
Could you please reupload the following links for KnowIt-VQA? Thank you very much! 
my email is 643678105@qq.com

**Comment by noagarcia** [comment]
Hi, sorry for the late response. 

Here are the new links:

https://drive.google.com/file/d/14bgcW4TFCIGj8KclHtj1HKRtZoATspkP/view?usp=sharing
https://drive.google.com/file/d/1hMLVYHEyCK_R-ns3NXkNdblApBq3FRmb/view?usp=sharing
