### ISSUE TITLE
Links for object relations are down

### ISSUE THREAD

**Issue by fan5303** [noagarcia/ROLL-VideoQA#3]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>knowit-vqa</BucketName>
<RequestId>HEMH2KMVCX1MJQ9S</RequestId>
<HostId>mXZFX0mG5Rv4qyCi6UCiAzTUO71VXioomrFmcNc98DzORR1vd7FhpumiLl34Ct/2IqO4UUwURuw=</HostId>
</Error>
Can you update the connection or send it to me privately? my email is 643678105@qq.com
Thank you !

**Comment by noagarcia** [comment]
Sorry about that, here is the new link for the object relations:

https://drive.google.com/file/d/1hMLVYHEyCK_R-ns3NXkNdblApBq3FRmb/view?usp=sharing
